### ISSUE TITLE
Reference sprites locally

### ISSUE THREAD

**Issue by SchillingSebastian** [openmaptiles/positron-gl-style#19]
The current sprites are referenced by url. Here is a to the [reference line](https://github.com/openmaptiles/positron-gl-style/blob/9ff6653df158aa95937a16d213ee6aa7b31b550a/style.json#L28)
If a newbie downloads the json, puts it into its tileserver-gl and there is no internet connection he receives 500er errors. 
Please provide the sprites as a local path OR alter the readme with a section regarding foreign urls.

See https://tileserver.readthedocs.io/en/latest/config.html#sprites for more information on how sprites are accessed by tileserver-gl.

I also opened an issue on tileserver-gl to provide better error logs for inaccessible network files https://github.com/maptiler/tileserver-gl/issues/557

**Comment by wwarne** [comment]
I got this problem but after investigation and searching I have realized that you shouldn't use `style.json` from this repository directly, because it's just a base template. You need to download style from Releases page
https://github.com/openmaptiles/positron-gl-style/releases - each release have few different styles and there is `style-local.json` which have local references to sprites and fonts.

**Comment by TomPohys** [comment]
For [new release v1.9](https://github.com/openmaptiles/positron-gl-style/releases/tag/v1.9) there is also `v1.9.zip` with content of `gh-pages` branch. 

Thanks @wwarne the investigation and reply.
